#
# MusterCull
# Bukkit plug-in default configuration file.
#

#limits:
#- type: CREEPER
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: SKELETON
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: SPIDER
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: ZOMBIE
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: SLIME
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: GHAST
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: PIGZOMBIE
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: ENDERMAN
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: CAVESPIDER
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: SILVERFISH
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: BLAZE
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: LAVASLIME
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: ENDERDRAGON
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: PIG
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: SHEEP
#  limit: 6
#  culling: SPAWN
#  range: 0
#- type: COW
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: CHICKEN
#  limit: 12
#  culling: SPAWN
#  range: 0
#- type: SQUID
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: WOLF
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: MUSHROOMCOW
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: SNOWMAN
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: OZELOT
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: VILLAGERGOLEM
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: VILLAGER
#  limit: 0
#  culling: SPAWN
#  range: 0

# The amount of damage to apply to mobs which are considered crowded under the
# DAMAGE method of culling.
damage: 6

# The percent chance that a mob will be damaged if crowded under the DAMAGE
# method of culling.
damage_chance: 75

# The number of ticks between invocations of the damage method for mobs.
ticks_between_damage: 20

# The number of entities to damage each round of the laborer.
damage_count: 1

# Whether to print a message when mobs are damaged. 
damage_notify: false

# Whether to enable the monster cull to each world's spawn level.
enable_monster_cull_to_spawn: true

# Maximum aggression factor for the monster cull pass.
max_monster_cull_aggression: 5

# Maximum number of monsters to kill in each monster cull pass
max_monster_cull_per_pass: 30

# The maximum number of living entities allowed to be loaded.
mob_max_mob: 10000

# mob_player_multiplier is multiplied by the number of online players.
# This number of how much smaller the mob cap is than mob_max_mob.
mob_player_multiplier: 5

# The number of ticks between invocations of the hardcap laborer for mobs.
# Minimum allowed tick gap is 200.  Values lower than this are ignored.
ticks_between_hard_cap: 300

# Number of entities before the damage laborer cares to run.
mob_limit: 1

# Percent of total entities a mob must be to be queued for damage.
mob_limit_percent: 1

# Type of culling logic to use in the case of a hard-cap cull.
# Options:  
#   RANDOM - will produce random culling with equal weight to every living entity.
#   PRIORITY - will produce priority based culling
#
# On priority based culling, we keep mobs in descending priority order.
#     Priority 1 - Named mob.
#     Priority 2 - High value persistent mobs (horses, villagers).
#     	Golems specifically not added as they can be auto'ed leading to an unfortunate culling scenario.
#     Priority 3 - tame wolves, colored sheep, tame cats.
#     Priority 4 - low value persistent mobs.
#     Non Priority - non persistent mobs.
hard_cap_culling_strategy: PRIORITY

# For the hard cap culling using priority culling strategy, what is the percent
#   of total mob population that a super-chunk (6 chunks) needs to contain in order to 
#   trigger a penalty purge.  This would require running a purge specifically against this 
#   chunk in order to get the mob-counts in this chunk back to the average mob-per-chunk
#   serverwide.
#
# Setting this value too high (disabling it in essence) will allow players to cause global cullings by 
#   by having high priority mobs (named/leash/horses) in large densities in their own chunks without
#   a problem.  By setting this to a reasonably percent, these player chunks would be first targeted
#   by a culling in order to bring them down to the average mob-per-chunk value.
#
# NOTE:  a value of 100 = 100%, a value of 15 = 15%, etc.
hard_cap_culling_priority_strategy_penalty_mob_percent: 15

